### ISSUE TITLE
iOS failing to build with latest commit

### ISSUE THREAD

**Issue by ItsCalebJones** [JackAppDev/flutter_iap#32]
Pulled the latest commit down to my project and iOS fails to build, looks like its caused by 30978567ece833026fdef435b48ba0cc1a3bd462

```
Error output from Xcode build:
↳
    ** BUILD FAILED **
    
Xcode's output:
↳
    === BUILD TARGET firebase_messaging OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/ALPCJONESM2/Development/flutter/.pub-cache/git/flutter_iap-9fead94f456194a797944451057e68aaadc5c86b/ios/Classes/SwiftFlutterIapPlugin.swift:96:20: error: empty collection literal requires an explicit type
        var products = []
                       ^~
    /Users/ALPCJONESM2/Development/flutter/.pub-cache/git/flutter_iap-9fead94f456194a797944451057e68aaadc5c86b/ios/Classes/SwiftFlutterIapPlugin.swift:102:61: error: ambiguous reference to member 'joined()'
            fetchResult("{\"status\":\"loaded\",\"products\":[\(products.joined(separator: ","))]}")
                                                                ^~~~~~~~
    Swift.Sequence:2:17: note: found this candidate
        public func joined() -> FlattenSequence<Self>
                    ^
    Swift.Sequence:2:17: note: found this candidate
        public func joined<Separator>(separator: Separator) -> JoinedSequence<Self> where Separator : Sequence, Separator.Element == Self.Element.Element
                    ^
    Swift.Sequence:2:17: note: found this candidate
        public func joined(separator: String = default) -> String
                    ^
    Swift.Collection:2:17: note: found this candidate
        public func joined() -> FlattenCollection<Self>
                    ^
    Swift.BidirectionalCollection:2:17: note: found this candidate
        public func joined() -> FlattenBidirectionalCollection<Self>
                    ^
    Swift.BidirectionalCollection:2:17: note: found this candidate
        public func joined(separator: String = default) -> String
```
